## Sigmoid A.F

In [1]:
import math


In [6]:
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [7]:
sigmoid(12)

0.9999938558253978

In [8]:
sigmoid(2)

0.8807970779778823

In [9]:
sigmoid(-10)

4.5397868702434395e-05

## Tanh A.F

In [10]:
def tanh(x):
    return (math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))

In [11]:
tanh(10)

0.9999999958776926

In [12]:
tanh(45)

1.0

In [14]:
tanh(-100)

-1.0

## RELU A.F

In [15]:
def relu(x):
    return (max(0,x))

In [16]:
relu(10)

10

In [17]:
relu(-2)

0

## Leaky relu A.F

In [18]:
def leaky_relu(x):
    return (max(0.1*x, x))

In [19]:
leaky_relu(100)

100

In [20]:
leaky_relu(-10)

-1.0

In [21]:
leaky_relu(-100)

-10.0

In [23]:
leaky_relu(-78)

-7.800000000000001

## Basic Matrix

In [24]:
import numpy as np

In [25]:
revenue = np.array([[180, 200, 220],[24,36,40],[12,18,20]])
expences = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [26]:
profit = revenue-expences
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [79]:
a = np.array([1000, 400, 1200])
b = np.array([[30, 40, 50],[5,10,15],[2,5,7]])

In [81]:
a.shape, b.shape

((3,), (3, 3))

In [33]:
c = a*b
c

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [34]:
np.dot(a,b)

array([34400, 50000, 64400])

In [35]:
a = np.array([75])
b = ([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])

In [36]:
a*b

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [40]:
a=np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
b=np.array([20, 30, 15])

In [41]:
a+b

array([[ 70,  90,  40],
       [ 30,  43,  20],
       [ 60, 100,  67]])

In [42]:
np.dot(a,b)

array([3175,  665, 3680])

## Loss Functions

In [43]:
#mean_absolute_error
import numpy as np
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [50]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
#         print(yt, yp)
        total_error += abs(yt-yp)
    print('Total error:', total_error)
    mae = total_error / len(y_true)
    print('MAE:', mae)
   
mae(y_true, y_predicted)   

Total error: 2.5
MAE: 0.5


In [51]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [52]:
0.7+0.3+1+0.5

2.5

In [53]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [54]:
np.mean(np.abs(y_predicted-y_true))

0.5

##  LOG Loss Function

In [55]:
np.log([0.00000000001])

array([-25.32843602])

In [57]:
epsilon=1e-15


In [59]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [69]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 0.0, 0.0, 0.999999999999999]

In [70]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12832\2029199556.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [63]:
np.log(y_predicted)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12832\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [64]:
#LOGLOSS FUNCTION
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.26978799617044

In [66]:
def log_loss(y_true, y_predicted_new):
    epsilon=1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new)) 
    
log_loss(y_true, y_predicted_new)


17.2696280766844

## Mean absolute error

In [71]:
import numpy as np
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [74]:
def mse(y_true, y_predicted):
    total_error=0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print('total error:', total_error)
    mse = total_error / len(y_true)
    print('MSE:', mse)
mse(y_true, y_predicted)      

total error: 1.83
MSE: 0.366


In [77]:
#by usin numpy
np.mean(np.square(y_true-y_predicted))

0.366